// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class HRMTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void tC01Login() {
    // Test name: TC-01-Login
    // Step # | name | target | value
    // 1 | open | https://opensource-demo.orangehrmlive.com/ | 
    driver.get("https://opensource-demo.orangehrmlive.com/");
    // 2 | click | css=#divUsername > .form-hint | 
    driver.findElement(By.cssSelector("#divUsername > .form-hint")).click();
    // 3 | type | id=txtUsername | Admin
    driver.findElement(By.id("txtUsername")).sendKeys("Admin");
    // 4 | click | id=txtPassword | 
    driver.findElement(By.id("txtPassword")).click();
    // 5 | type | id=txtPassword | admin123
    driver.findElement(By.id("txtPassword")).sendKeys("admin123");
    // 6 | click | id=btnLogin | 
    driver.findElement(By.id("btnLogin")).click();
    // 7 | waitForElementPresent | xpath=//h1[contains(.,'Dashboard')] | 1
    {
      WebDriverWait wait = new WebDriverWait(driver, 0);
      wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("//h1[contains(.,\'Dashboard\')]")));
    }
    // 8 | echo | Login PASSED | 
    System.out.println("Login PASSED");
  }
  @Test
  public void tC02ExtractEmployeeName() {
    // Test name: TC-02-ExtractEmployeeName
    // Step # | name | target | value
    // 1 | open | https://opensource-demo.orangehrmlive.com/index.php/dashboard | 
    driver.get("https://opensource-demo.orangehrmlive.com/index.php/dashboard");
    // 2 | mouseOver | id=menu_admin_viewAdminModule | 
    {
      WebElement element = driver.findElement(By.id("menu_admin_viewAdminModule"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 3 | mouseOver | id=menu_admin_UserManagement | 
    {
      WebElement element = driver.findElement(By.id("menu_admin_UserManagement"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 4 | click | id=menu_admin_viewSystemUsers | 
    driver.findElement(By.id("menu_admin_viewSystemUsers")).click();
    // 5 | storeText | xpath=//td[contains(.,'Anthony Nolan')] | empl
    vars.put("empl", driver.findElement(By.xpath("//td[contains(.,\'Anthony Nolan\')]")).getText());
    // 6 | mouseOver | id=menu_leave_viewLeaveModule | 
    {
      WebElement element = driver.findElement(By.id("menu_leave_viewLeaveModule"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 7 | click | id=menu_leave_assignLeave | 
    driver.findElement(By.id("menu_leave_assignLeave")).click();
    // 8 | click | id=assignleave_txtEmployee_empName | 
    driver.findElement(By.id("assignleave_txtEmployee_empName")).click();
    // 9 | type | id=assignleave_txtEmployee_empName | ${empl}
    driver.findElement(By.id("assignleave_txtEmployee_empName")).sendKeys(vars.get("empl").toString());
    // 10 | click | xpath=//*[@id="assignleave_txtLeaveType"]/option[10] | 
    driver.findElement(By.xpath("//*[@id=\"assignleave_txtLeaveType\"]/option[10]")).click();
    // 11 | click | css=li:nth-child(4) > .ui-datepicker-trigger | 
    driver.findElement(By.cssSelector("li:nth-child(4) > .ui-datepicker-trigger")).click();
    // 12 | click | linkText=31 | 
    driver.findElement(By.linkText("31")).click();
    // 13 | click | css=.ui-datepicker-trigger:nth-child(3) | 
    driver.findElement(By.cssSelector(".ui-datepicker-trigger:nth-child(3)")).click();
    // 14 | click | css=.ui-icon-circle-triangle-e | 
    driver.findElement(By.cssSelector(".ui-icon-circle-triangle-e")).click();
    // 15 | click | linkText=13 | 
    driver.findElement(By.linkText("13")).click();
    // 16 | type | id=assignleave_txtComment | Hello Kitty!
    driver.findElement(By.id("assignleave_txtComment")).sendKeys("Hello Kitty!");
    // 17 | echo | EmployeeName: ${empl} | 
    System.out.println("EmployeeName: vars.get("empl").toString()");
    // 18 | echo | ExtractName PASSED | 
    System.out.println("ExtractName PASSED");
  }
  @Test
  public void tC03AddJob() {
    // Test name: TC-03-AddJob
    // Step # | name | target | value
    // 1 | open | https://opensource-demo.orangehrmlive.com/index.php/admin/viewJobTitleList | 
    driver.get("https://opensource-demo.orangehrmlive.com/index.php/admin/viewJobTitleList");
    // 2 | store | QA-AutoTest | a
    vars.put("a", "QA-AutoTest");
    // 3 | store | 0 | x
    vars.put("x", "0");
    // 4 | times | 5 | 
    Integer times = 5;
    for(int i = 0; i < times; i++) {
      // 5 | executeScript | return Math.floor(${x})+1 | y
      vars.put("y", js.executeScript("return Math.floor(arguments[0])+1", vars.get("x")));
      // 6 | click | id=btnAdd | 
      driver.findElement(By.id("btnAdd")).click();
      // 7 | click | id=jobTitle_jobTitle | 
      driver.findElement(By.id("jobTitle_jobTitle")).click();
      // 8 | type | id=jobTitle_jobTitle | ${a}${y}
      driver.findElement(By.id("jobTitle_jobTitle")).sendKeys(vars.get("a").toString()${y});
      // 9 | store | ${y} | x
      vars.put("x", "vars.get("y").toString()");
      // 10 | click | id=jobTitle_jobDescription | 
      driver.findElement(By.id("jobTitle_jobDescription")).click();
      // 11 | type | id=jobTitle_jobDescription | 5x
      driver.findElement(By.id("jobTitle_jobDescription")).sendKeys("5x");
      // 12 | click | id=jobTitle_note | 
      driver.findElement(By.id("jobTitle_note")).click();
      // 13 | type | id=jobTitle_note | 5x
      driver.findElement(By.id("jobTitle_note")).sendKeys("5x");
      // 14 | click | css=.largeTextBox:nth-child(4) | 
      driver.findElement(By.cssSelector(".largeTextBox:nth-child(4)")).click();
      // 15 | click | id=btnSave | 
      driver.findElement(By.id("btnSave")).click();
      // 16 | end |  | 
    }
    // 17 | echo | AddJob PASSED | 
    System.out.println("AddJob PASSED");
  }
  @Test
  public void tC09Logout() {
    // Test name: TC-09-Logout
    // Step # | name | target | value
    // 1 | open | https://opensource-demo.orangehrmlive.com/index.php/dashboard | 
    driver.get("https://opensource-demo.orangehrmlive.com/index.php/dashboard");
    // 2 | click | id=welcome | 
    driver.findElement(By.id("welcome")).click();
    // 3 | click | linkText=Logout | 
    driver.findElement(By.linkText("Logout")).click();
    // 4 | echo | Logout PASSED | 
    System.out.println("Logout PASSED");
  }
}
